### PR TITLE
Fix #69: Support for PowerAuth mobile SDK 1.7.x

### LINKED ISSUE #69: Support for PowerAuth mobile SDK 1.7.x
Upgrade project to support PowerAuth mobile SDK 1.7.x

### PR DESCRIPTION
**Pull request by hvge**
This PR adds support for PowerAuth mobile SDK 1.7.x. 

Note that this change only solves compatibility with PA-SDK, but the project itself requires a more touch to update gradle dependencies.

### CODE REVIEW

**Comment by hvge** [comment]
So, It looks like I have to also upgrade the gradle dependencies :)

**Review by petrdvorak — APPROVED** [review]
Looks great

**Review by kober32 — APPROVED** [review]
👍🏻

**Comment by kober32** [comment]
👍🏻 gradle changes looks OK

**Pull request merged**
